-- Schema inicial do CampusGigs (CP1).
-- Qualquer mudança daqui pra frente vira uma nova migration.

CREATE TABLE usuario (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome          VARCHAR(120)  NOT NULL,
    email         VARCHAR(120)  NOT NULL,
    senha         VARCHAR(255)  NOT NULL,
    papel         VARCHAR(20)   NOT NULL,
    cep           VARCHAR(8),
    logradouro    VARCHAR(150),
    bairro        VARCHAR(100),
    cidade        VARCHAR(100),
    uf            CHAR(2),
    criado_em     TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_usuario_email UNIQUE (email),
    CONSTRAINT ck_usuario_papel CHECK (papel IN ('ADMIN', 'USER'))
);

CREATE TABLE servico (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prestador_id  BIGINT        NOT NULL,
    titulo        VARCHAR(150)  NOT NULL,
    descricao     TEXT          NOT NULL,
    categoria     VARCHAR(80)   NOT NULL,
    preco         NUMERIC(10, 2) NOT NULL,
    situacao      VARCHAR(20)   NOT NULL,
    criado_em     TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_servico_prestador FOREIGN KEY (prestador_id) REFERENCES usuario (id),
    CONSTRAINT ck_servico_situacao CHECK (situacao IN ('ATIVO', 'PAUSADO', 'ENCERRADO')),
    CONSTRAINT ck_servico_preco CHECK (preco >= 0)
);

CREATE TABLE contratacao (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    servico_id      BIGINT      NOT NULL,
    contratante_id  BIGINT      NOT NULL,
    situacao        VARCHAR(20) NOT NULL,
    criado_em       TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_contratacao_servico FOREIGN KEY (servico_id) REFERENCES servico (id),
    CONSTRAINT fk_contratacao_contratante FOREIGN KEY (contratante_id) REFERENCES usuario (id),
    CONSTRAINT ck_contratacao_situacao CHECK (situacao IN ('SOLICITADA', 'ACEITA', 'CONCLUIDA', 'CANCELADA'))
);

CREATE INDEX idx_servico_prestador ON servico (prestador_id);
CREATE INDEX idx_servico_situacao ON servico (situacao);
CREATE INDEX idx_contratacao_servico ON contratacao (servico_id);
CREATE INDEX idx_contratacao_contratante ON contratacao (contratante_id);
